name: Build and Deploy Cloud Project ( FII )

on:
  push:
    branches:
      - main 
  workflow_dispatch: 

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest 
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v4

    - name: Python version
      uses: actions/setup-python@v5
      with:
        python-version: '3.11' 

    - name: Create and start virtual environment
      run: |
        python -m venv venv
        source venv/bin/activate

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Testing
      run: PYTHONPATH=. pytest 

    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }} 

    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v3
      with:
        app-name: 'cloud-application' 
        package: '.'
     
        app-settings-json: |
          [
            { "name": "TRANSLATOR_API_KEY", "value": "${{ secrets.TRANSLATOR_API_KEY }}", "slotSetting": false },
            { "name": "TRANSLATOR_API_ENDPOINT", "value": "${{ secrets.TRANSLATOR_API_ENDPOINT }}", "slotSetting": false },
            { "name": "TRANSLATOR_API_REGION", "value": "${{ secrets.TRANSLATOR_API_REGION }}", "slotSetting": false },
            { "name": "FLASK_ENV", "value": "production", "slotSetting": false }
          ]
      
    - name: Logout from Azure
      run: |
        az logout --username ${{ secrets.AZURE_LOGIN_USERNAME_IF_NEEDED_FOR_LOGOUT }} || echo "Logout failed or not applicable"
    